name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */8 * * *'  # run every 8 hours
  workflow_dispatch:  # allow manual trigger

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Wake up Streamlit app
        run: |
          echo "🤖 Starting intelligent wake-up process..."
          npm run wake-up

      - name: Upload screenshot (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-screenshot
          path: app_status.png
          retention-days: 1
